### ISSUE TITLE
Not starting on zero

### ISSUE THREAD

**Issue by jbonigomes** [FDIM/md-range-slider#1]
Thanks FDIM, great work, exactly what I need for my project, however, I believe I am doing something wrong when using your directive, I need it to range from 1915 to 2016, the left slider works fine but the right slider range is really small, I have a codepen to illustrate it better:

http://codepen.io/jbonigomes/pen/LNozNR

Thanks

**Comment by FDIM** [comment]
I'll have a look when I get home, in the meantime thanks! you just gave me an idea for birthdate selection in one of my projects.

**Comment by jbonigomes** [comment]
Thanks @FDIM

**Comment by FDIM** [comment]
To fix the problem you experienced replace following line:

```
$scope.upperWidth = ((($scope.max-($scope.lowerValue + $scope.step))/$scope.max) * 100) + "%";
```

to

```
$scope.upperWidth = ((($scope.max-($scope.lowerValue + $scope.step))/($scope.max-$scope.min) * 100) + "%";
```

Note that bower package (and compat branch) is also updated.

**Comment by jbonigomes** [comment]
Thanks @FDIM, keep up with the good work. Much appreciated.
