### ISSUE TITLE
Bug min value

### ISSUE THREAD

**Issue by douglasscriptore** [FDIM/md-range-slider#2]
I'm in trouble with the lowest value , seek a new data min and max in the database , however the min value is always with the initial value , it does not change

**Comment by douglasscriptore** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/3733634/15687320/7b9892aa-274a-11e6-8fa9-e64b5e08ddbb.png)

**Comment by FDIM** [comment]
Thanks for reporting :+1:

**Comment by douglasscriptore** [comment]
@FDIM thx
