### ISSUE TITLE
Strict mode used globally

### ISSUE THREAD

**Issue by szuperaz** [FDIM/md-range-slider#3]
Hi,

I noticed that you declare strict mode globally, which can cause errors when your library concateneted and minified (I use gulp-minify) together with other libraries, which don't support strict mode. (I tested it by removing `'use strict'` from the `md-range-slider.js` and I didn't get the error.)
If you could declare it inside the function, that would be much help.

Thanks,
Zita

**Comment by FDIM** [comment]
Thanks for pointing that out, it is now corrected
