### ISSUE TITLE
Putting edges together then separating with upper causes lower to move

### ISSUE THREAD

**Issue by Roundaround** [FDIM/md-range-slider#4]
If you drag the upper limit down to the lower one, let go, then click on it again and drag it up, the lower limit will slide out to match it when you release the mouse button.

**Comment by Roundaround** [comment]
Actually, this might just be that it's dragging the lower one instead of the upper one, which makes the upper snap to it afterward.

**Comment by FDIM** [comment]
I just tried it out - it is definitely a strange quirk, which only happens if upper value == lower value. I'll have a look and prevent this from happening.
