### ISSUE TITLE
NAna appears as the buttons are dragged for date range

### ISSUE THREAD

**Issue by rehans516** [FDIM/md-range-slider#7]
Thanks for creating such a widget. i have modified to use it for letting users provide input as date ranges but while testing as soon as i started dragging the buttons for creating a range, the dates which were there at the start changed into a value of "NaNa". I am using angular 1.6.4 and materials 1.1.1 . what could be the issue?

**Comment by FDIM** [comment]
This component only works with numeric values, thus you cannot use date object for upper/lower-value
